server:
  port: 8080

spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.81.247.107:3307/stand?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

yk:
  swagger:
    enabled: true
    basePackage: com.yk.stand
    title: Stand项目Api管理
    contact:
      name: yangke
      url: https://anyong.work
      email: 1403447720@qq.com
    description: dev
